id: P009453
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22167
  title: མི་ཕམ་མཁས་འཇུག
  author: ''
  volumes:
    c91adad143544290a99d5c74ddc39a15:
      image_group_id: I1KG10374
      title: ''
      volume_number: 1
      total_pages: 460
      base_file: v001.txt
